### ISSUE TITLE
SpectralFrame ignoring reference_position

### ISSUE THREAD

**Issue by braingram** [spacetelescope/gwcs#436]
While testing schema with defaults I encountered unexpected behavior when loading an asdf file with a saved spectral frame.

First running:
```python
import asdf
import gwcs

tree = {
    'sf': gwcs.coordinate_frames.SpectralFrame(
        reference_position="GEOCENTER")
}
af = asdf.AsdfFile(tree)
af.write_to('foo.asdf')
```

Will generate an asdf file with contents:
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
  name: asdf, version: 2.13.1.dev71+gf8efb2a.d20221012}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    software: !core/software-1.0.0 {name: asdf, version: 2.13.1.dev71+gf8efb2a.d20221012}
  - !core/extension_metadata-1.0.0
    extension_class: gwcs.extension.GWCSExtension
    software: !core/software-1.0.0 {name: gwcs, version: 0.17.1}
sf: !<tag:stsci.edu:gwcs/spectral_frame-1.0.0>
  axes_names: ['']
  axes_order: [0]
  axis_physical_types: ['custom:dimensionless']
  name: SpectralFrame
  reference_position: geocenter
  unit: [!unit/unit-1.0.0 '']
...
```

However, loading this file ignores `reference_position` entirely:
```python
import asdf

af = asdf.open('foo.asdf')
print(af['sf'].reference_position)
```
Prints `None`

I believe the cause of the error is that `reference_position` is not propagated through `FrameConverter._from_yaml_tree`:
https://github.com/spacetelescope/gwcs/blob/baef5728b8cf41ec4c1997911e2bc9460e8d480a/gwcs/converters/wcs.py#L46-L69

called from `SpectralFrameConverter`:
https://github.com/spacetelescope/gwcs/blob/baef5728b8cf41ec4c1997911e2bc9460e8d480a/gwcs/converters/wcs.py#L135

I looked back several versions and believe this issue might be older than 0.9 (for older versions the issue was with the old asdf types instead of converters).
